# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir P:/ENEL373/theALUProject/theALUProject.cache/wt [current_project]
set_property parent.project_path P:/ENEL373/theALUProject/theALUProject.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
read_vhdl -library xil_defaultlib {
  P:/ENEL373/Lab_A01_group_3/ALU.vhd
  P:/ENEL373/Lab_A01_group_3/regO.vhd
  P:/ENEL373/theALUProject/theALUProject.srcs/sources_1/new/debounce.vhd
  P:/ENEL373/Lab_A01_group_3/clkDiv100to500.vhd
  P:/ENEL373/Lab_A01_group_3/seg7_mux.vhd
  P:/ENEL373/seg7.vhd
  P:/ENEL373/Lab_A01_group_3/regG.vhd
  P:/ENEL373/Lab_A01_group_3/regB.vhd
  P:/ENEL373/Lab_A01_group_3/regA.vhd
  P:/ENEL373/Lab_A01_group_3/FSM.vhd
  P:/ENEL373/BIN2BCD.vhd
  P:/ENEL373/Lab_A01_group_3/display_Mode_Select_Mux.vhd
  P:/ENEL373/Lab_A01_group_3/main.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc P:/ENEL373/Lab_A01_group_3/Nexys4DDR_Master.xdc
set_property used_in_implementation false [get_files P:/ENEL373/Lab_A01_group_3/Nexys4DDR_Master.xdc]


synth_design -top main -part xc7a100tcsg324-3


write_checkpoint -force -noxdef main.dcp

catch { report_utilization -file main_utilization_synth.rpt -pb main_utilization_synth.pb }
